export const A_DOWN = 'A_DOWN'; 
export const B_DOWN = 'B_DOWN';
export const BUTTON_RELEASE = 'BUTTON_RELEASE';
export const STICK_MOVE = 'STICK_MOVE'; 
export const STICK_RELEASE = 'STICK_RELEASE'; 

export const ENTER_ID = 'ENTER_ID';

export const REQUEST_START = 'REQUEST_START';
export const REQUEST_FAILED = 'REQUEST_FAILED';

export const WS_CONNECT =  'WS_CONNECT';
export const WS_CONNECTED = 'WS_CONNECTED';
export const WS_ERROR = 'WS_ERROR';
export const WS_DISCONNECT = 'WS_DISCONNECT';
export const WS_DISCONNECTED = 'WS_DISCONNECTED';

export const UNITY_CONNECT_START = 'UNITY_CONNECT_START';
export const UNITY_CONNECT_SUCCEEDED = 'UNITY_CONNECT_SUCCEEDED';
export const UNITY_CONNECT_FAILED = 'UNITY_CONNECT_FAILED';